/**
* Generated by odin v1.3.8.
* Don't edit!
 */
package httpsrv

import (
	"net/http"

	"github.com/youminxue/odin/framework/rest"
)

type TestsvcHandler interface {
	PageUsers(w http.ResponseWriter, r *http.Request)
}

func Routes(handler TestsvcHandler) []rest.Route {
	return []rest.Route{
		{
			Name:        "PageUsers",
			Method:      "POST",
			Pattern:     "/page/users",
			HandlerFunc: handler.PageUsers,
		},
	}
}

var RouteAnnotationStore = rest.AnnotationStore{}
